name: Deploy to Azure Container Instances

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/mi-app:latest .
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/mi-app:latest

      - name: Deploy to Azure Container Instance
        run: |
          az container create \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --name ${{ secrets.ACI_NAME }} \
            --image ${{ secrets.ACR_NAME }}.azurecr.io/mi-app:latest \
            --registry-login-server ${{ secrets.ACR_NAME }}.azurecr.io \
            --registry-username ${{ secrets.AZURE_CLIENT_ID }} \
            --registry-password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --dns-name-label mi-app-ricardo-123456 \
            --ports 3000 \
            --restart-policy Always
